#pragma once

#define DRIVER_SYM_LINK L"\\\\.\\KProtect"

#define ROOT_PATH L"\\REGISTRY\\MACHINE\\SOFTWARE\\UProtect"

#define MINIFILTER_INFO_ROOT_PATH L"SOFTWARE\\UProtect\\MINIFILTER"
#define DRIVER_MINI_FILTER_INFO_ROOT_PATH L"\\Registry\\Machine\\Software\\UProtect\\MINIFILTER"

#define ALL_PROGRAMS_INSTALL_PATH L"\\Device\\HarddiskVolume3\\UPROTECT\\bin"

#define REG_TRIE_SIZE_VALUE_NAME L"Size"
#define REG_TRIE_WCHAR_RANGE_VALUE_NAME L"Range"
#define REG_SUB_TRIE_INFO_NAME L"Info"

#define DEFAULT_BUFFER_SIZE (1 << 10) 

#define MAX_PATH_LEN 256
#define MAX_PATHS DEFAULT_BUFFER_SIZE 


#define DEVICE_UPROTECT 0x800

#define RELOAD_MINIFILTER_POLICY_CONTROL_CODE 0x800
#define CONTROL_APP_LOADED_CONTROL_CODE 0x801
#define CONTROL_APP_UNLOADED_CONTROL_CODE 0x802
#define DRIVER_UNLOAD_CONTROL_CODE 0x803
#define DRIVER_LOAD_CONTROL_CODE 0x804

#define IOCTL_RELOAD_MINIFILTER_POLICY CTL_CODE(DEVICE_UPROTECT, RELOAD_MINIFILTER_POLICY_CONTROL_CODE, METHOD_NEITHER, FILE_ANY_ACCESS)
#define IOCTL_DLL_LOAD CTL_CODE(DEVICE_UPROTECT, CONTROL_APP_LOADED_CONTROL_CODE, METHOD_NEITHER, FILE_ANY_ACCESS)
#define IOCTL_DLL_UNLOAD CTL_CODE(DEVICE_UPROTECT, CONTROL_APP_UNLOADED_CONTROL_CODE, METHOD_NEITHER, FILE_ANY_ACCESS)
#define IOCTL_DRIVER_UNLOAD CTL_CODE(DEVICE_UPROTECT, DRIVER_UNLOAD_CONTROL_CODE, METHOD_NEITHER, FILE_ANY_ACCESS)
#define IOCTL_DRIVER_LOAD CTL_CODE(DEVICE_UPROTECT, DRIVER_LOAD_CONTROL_CODE , METHOD_NEITHER, FILE_ANY_ACCESS)
